### ISSUE TITLE
Configurar o GitHub Actions

### ISSUE THREAD

**Issue by LucasMBalieiro** [LucasMBalieiro/ES2_2023-2_shuup#13]

**Comment by LucasMBalieiro** [comment]
O Github Actions não possui suporte para Python 3.6, tornando impossível implementar um CI funcional, visto que o projeto possui dependências especificas para essa versão de Python.

https://github.com/actions/setup-python/issues/665 https://github.com/actions/setup-python/issues/561 https://github.com/actions/setup-python/issues/480 https://github.com/actions/setup-python/issues/355 https://github.com/actions/setup-python/issues/544

**Comment by YaboiAst** [comment]
Confirmado. Não será implementado.
