### ISSUE TITLE
Mudança 1

### ISSUE THREAD

**Issue by YaboiAst** [LucasMBalieiro/ES2_2023-2_shuup#14]

**Comment by LucasMBalieiro** [comment]
Erro encontrado durante o set e post de um novo produto.

Descriçao: O projeto aceita valores negativos para o preço.

**Comment by LucasMBalieiro** [comment]
Review do codigo disposto:

-Problema parcialmente solucionado, ao tentar setar um produto de valor negativo, dispara mensagem de erro HTML impedindo sua implementaçao, porem o produto nao pode mais ser acessado para ediçao.
